"""
Django settings for zhongyao project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


def env_bool(name, default=False):
    """Read a boolean setting from the environment."""
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def project_path(value):
    """Resolve relative configuration paths from the project root."""
    path = Path(value).expanduser()
    return path if path.is_absolute() else BASE_DIR / path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dj3j)^f!i4(3s)hn5&_vs53!h0hc-ft=1!$v9(8yo#ea@bjt$4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 自己的应用
    'user.apps.UserConfig',
    'predict.apps.PredictConfig',
    'chat.apps.ChatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zhongyao.urls'
# 如果用户继承了AbstractUser，修改原生auth_user的模型的话就需要加这个配置
AUTH_USER_MODEL = 'user.UserProfile'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 如果要在页面里面进行引用图片的话，就必须在这里添加配置
                'django.template.context_processors.media' # 在模板中可以使用{{MEDIA_URL}}
            ],
        },
    },
]

WSGI_APPLICATION = 'zhongyao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': project_path(os.environ.get('DJANGO_SQLITE_PATH', 'blog')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# 配置语言，时区
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# 配置静态文件夹路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置媒体文件路径 上传文件的目录
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

PICTURE = BASE_DIR / 'pictures'

# Machine-learning models.  Keep the BERT model outside the source tree and
# point CHAT_MODEL_DIR at a complete local Hugging Face model directory.
CHAT_MODEL_DIR = project_path(os.environ.get('CHAT_MODEL_DIR', 'models/bert-base-chinese'))
CHAT_MODEL_WEIGHTS = project_path(os.environ.get('CHAT_MODEL_WEIGHTS', 'chat/good.bin'))
CHAT_MODEL_DEVICE = os.environ.get('CHAT_MODEL_DEVICE', 'cpu')
CHAT_MODEL_LOCAL_FILES_ONLY = env_bool('CHAT_MODEL_LOCAL_FILES_ONLY', True)
CHAT_DATA_DIR = BASE_DIR / 'chat' / 'data'

# Knowledge graph service.
NEO4J_URI = os.environ.get('NEO4J_URI', 'bolt://localhost:7687')
NEO4J_USERNAME = os.environ.get('NEO4J_USERNAME', 'neo4j')
NEO4J_PASSWORD = os.environ.get('NEO4J_PASSWORD', '')
NEO4J_DATABASE = os.environ.get('NEO4J_DATABASE', 'neo4j')

# Image-recognition model.
PREDICT_MODEL_WEIGHTS = project_path(os.environ.get('PREDICT_MODEL_WEIGHTS', 'predict/model.pth'))
PREDICT_CLASS_INDICES = project_path(os.environ.get('PREDICT_CLASS_INDICES', 'predict/class_indices.json'))
PREDICT_MODEL_DEVICE = os.environ.get('PREDICT_MODEL_DEVICE', 'cpu')
